chats/urls.py
from django.urls import path
from .views import ChatView

app_name = 'chats'

urlpatterns = [
    path('', ChatView.as_view(), name='chats')
]

musics/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView

)
from django.views.generic import TemplateView
from django.urls import path, include
from leads.views import LandingPageView, SignUpView

admin.site.site_header = 'Django_Test Enterprise'
admin.site.index_title = 'Django_Test Administration'


urlpatterns = [
    path('admin/', admin.site.urls),
    
    # Local apps
    path('', LandingPageView.as_view(), name='landing-page'),
    path('song/', include('songs.urls', namespace='songs')),
    path('leads/', include("leads.urls", namespace='leads')),
    path("agents/", include("agents.urls", namespace='agents')),

    # Registration URL - inherited for django.contrib.auths views
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    
    
    # third party
    path('accounts/', include('allauth.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path("__reload__/", include("django_browser_reload.urls")),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

pharmaceuticals/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
#from django.conf.urls.defaults import *
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView

)
from django.views.generic import TemplateView
from django.urls import path, include
from leads.views.leads import LandingPageView, SignUpView

admin.site.site_header = 'MedConnect Pharmaceuticals'
admin.site.index_title = 'Django_Test Administration'


urlpatterns = [
    path('admin/', admin.site.urls),

    # Local apps
    path('', LandingPageView.as_view(), name='landing-page'),
    path('song/', include('songs.urls', namespace='songs')),
     path('accounts/', include('allauth.urls')),
    path('leads/', include("leads.urls", namespace='leads')),
    path("agents/", include("agents.urls", namespace='agents')),
    path('pharmcare/', include('pharmcare.urls', namespace='pharmcare')),
    path('chats/', include('chats.urls', namespace='chats')),
    path('staff-attendance/', include('staff.urls', namespace='staff')),



    # Registration URL - inherited for django.contrib.auths views
   # path('login/', LoginView.as_view(), name='login'),
    #path('logout/', LogoutView.as_view(), name='logout'),
    #path('signup/', SignUpView.as_view(), name='signup'),
    #path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    #path('password-reset-done/', PasswordResetDoneView.as_view(),
     #    name='password_reset_done'),
   # path('password-reset-confirm/<uidb64>/<token>/',
    #     PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    #path('password-reset-complete/', PasswordResetCompleteView.as_view(),
     #    name='password_reset_complete'),


    # third party
    path('accounts/', include('allauth.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path("__reload__/", include("django_browser_reload.urls")),


]


handler404 = 'pharmcare.views.patient_details.error_404'
handler500 =  'pharmcare.views.patient_details.error_500'
handler403 =  'pharmcare.views.patient_details.error_403'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

pharmcare/urls.py
from django.urls import path
from pharmcare.views.pharmacists import *

from pharmcare.views.patient_details import (
    PatientDetailListView,
    PatientDetailCreateView,
    PatientDetailView,
    UpdatePatientDetailView,
    DeletePatientDetailView,
)

from pharmcare.views.medication_history import (
    MedicationHistoryListView,
    MedicationHistoryCreateView,
    MedicationHistoryDeleteView,
    MedicationHistoryUpdateView,
    MedicationHistoryDetailView,
)

from pharmcare.views.medication_changes import (
    MedicationChangesListView,
    MedicationChangesCreateView,
    MedicationChangesDetailView,
    MedicationChangesUpdateView,
    MedicationChangesDeleteView,
)
from pharmcare.views.monitoring_plans import (

    MonitoringPlanListView,
    MonitoringPlanCreateView,
    MonitoringPlanDetailView,
    MonitoringPlanUpdateView,
    MonitoringPlanDeleteView,

)

from pharmcare.views.analysis_of_cp import (

    AnalysisOfClinicalProblemListView,
    AnalysisOfClinicalProblemCreateView,
    AnalysisOfClinicalProblemDetailView,
    AnalysisOfClinicalProblemUpdateView,
    AnalysisOfClinicalProblemDeleteView,

)

from pharmcare.views.pharmaceutical_care_plan import (
    PatientSummaryListView,
    PatientSummaryCreateView,
    delete_patient_summary,
    PatientSummaryDetailView,
    PatientSummaryUpateView,

)

from pharmcare.views.progress_notes import (

    ProgressNoteListView,
    ProgressNoteCreateView,
    ProgressNoteDetailView,
    ProgressNoteUpdateView,
    ProgressNoteDeleteView,
)

from pharmcare.views.follow_up_plans import (

    FollowUpPlanListView,
    FollowUpPlanCreateView,
    FollowUpPlanDetailView,
    FollowUpPlanUpdateView,
    FollowUpPlanDeleteView,

)

from pharmcare.views.patients import (
    PatientListView,
    PatientCreateView,
    PatientUpateView,
    delete_patient_view,
    PatientsDetailView
)


app_name = 'pharmcare'

urlpatterns = [
    # Pharmcare URI

    # pharmcare list URIs
    path('', PatientDetailListView.as_view(), name='patient'),
    path('medication-history/', MedicationHistoryListView.as_view(),
         name='medication-history'),
    path('patient-info/', PatientListView.as_view(), name='patient-info'),
    path('patient-list/', PatientSummaryListView.as_view(), name='patients'),
    path('medication-changes/', MedicationChangesListView.as_view(),
         name='medication-changes'),
    path('analysis-of-clincal-problem/',
         AnalysisOfClinicalProblemListView.as_view(), name='analysis-of-cp'),
    path('monitoring-plan/', MonitoringPlanListView.as_view(),
         name='monitoring-plan'),
    path('follow-up-plan/', FollowUpPlanListView.as_view(), name='follow-up-plan'),
    path('progress-note/', ProgressNoteListView.as_view(), name='progress-notes'),


    path('pharmacist/', PharmacistListView.as_view(), name="pharmacist-list"),


    # pharmcare create uris
    path('patient-create/', PatientDetailCreateView.as_view(), name='patient-create'),
    path('patient-info-create/', PatientCreateView.as_view(),
         name='patients-info-create'),
    path('medication-history-create/', MedicationHistoryCreateView.as_view(),
         name='medication-history-create'),
    path('patients-create/',  PatientSummaryCreateView.as_view(),
         name='patients-create'),
    path('medication-changes-create/', MedicationChangesCreateView.as_view(),
         name='medication-changes-create'),
    path('analysis-of-clincal-problem-create/',
         AnalysisOfClinicalProblemCreateView.as_view(), name='analysis-of-cp-create'),
    path('monitoring-plan-create/', MonitoringPlanCreateView.as_view(),
         name='monitoring-plan-create'),
    path('follow-up-plan-create/', FollowUpPlanCreateView.as_view(),
         name='follow-up-plan-create'),
    path('progress-note-create/', ProgressNoteCreateView.as_view(),
         name='progress-note-create'),

    path('pharmacist-create/', PharmacistCreateView.as_view(),
         name="pharmacist-create"),


    # pharmcare detail uris
    path('<str:slug>/', PatientDetailView.as_view(), name='patient-detail'),
    path('patient-info/<str:slug>/', PatientsDetailView.as_view(),
         name='patients-info-detail'),
    path("medication-changes/<str:slug>/",
         MedicationChangesDetailView.as_view(), name='medication-changes-detail'),
    path('medication-history/<int:pk>/', MedicationHistoryDetailView.as_view(),
         name='medication-history-detail'),

    path("analysis-of-clincal-problem/<str:slug>/",
         AnalysisOfClinicalProblemDetailView.as_view(), name='analysis-of-cp-detail'),
    path('patient-list/<int:pk>/',
         PatientSummaryDetailView.as_view(), name='patients-detail'),

    path("monitoring-plan/<str:slug>/",
         MonitoringPlanDetailView.as_view(), name='monitoring-plan-detail'),
    path("follow-up-plan/<str:slug>/", FollowUpPlanDetailView.as_view(),
         name='follow-up-plan-detail'),
    path("progress-note/<str:slug>/", ProgressNoteDetailView.as_view(),
         name='progress-note-detail'),

    path("pharmacist/<str:slug>/", PharmacistDetailView.as_view(),
         name='pharmacist-detail'),

    # pharmcare update uris
    path('<str:slug>/patient-update/',
         UpdatePatientDetailView.as_view(), name='patient-update'),
    path('medication-history/<int:pk>/medication-history-update/',
         MedicationHistoryUpdateView.as_view(), name='medication-history-update'),
    path('patient-list/<int:pk>/patients-update/',
         PatientSummaryUpateView.as_view(), name='patients-update'),
    path('patient-info/<str:slug>/update/',
         PatientUpateView.as_view(), name='patients-info-update'),
    path("medication-changes/<str:slug>/update/",
         MedicationChangesUpdateView.as_view(), name='medication-changes-update'),
    path("analysis-of-clincal-problem/<str:slug>/update/",
         AnalysisOfClinicalProblemUpdateView.as_view(), name='analysis-of-cp-update'),
    path("monitoring-plan/<str:slug>/update/",
         MonitoringPlanUpdateView.as_view(), name='monitoring-plan-update'),
    path("follow-up-plan/<str:slug>/update/",
         FollowUpPlanUpdateView.as_view(), name='follow-up-plan-update'),
    path("progress-note/<str:slug>/update/",
         ProgressNoteUpdateView.as_view(), name='progress-note-update'),



    path("pharmacist/<str:slug>/update/", PharmacistUpdateView.as_view(),
         name='pharmacist-update'),


    # pharmcare delete uris
    path('<str:slug>/patient-delete/',
         DeletePatientDetailView.as_view(), name='patient-delete'),

    path('medication-history/<int:pk>/medication-history-delete/',
         MedicationHistoryDeleteView.as_view(), name='medication-history-delete'),

    path('patient-list/<int:pk>/patients-delete/',
         delete_patient_summary, name='patients-delete'),
    path('patients-info/<str:slug>/delete/',
         delete_patient_view, name='patient-info-delete'),

    path("medication-changes/<str:slug>/delete/",
         MedicationChangesDeleteView.as_view(), name='medication-changes-delete'),
    path("analysis-of-clincal-problem/<str:slug>/delete/",
         AnalysisOfClinicalProblemDeleteView.as_view(), name='analysis-of-cp-delete'),
    path("monitoring-plan/<str:slug>/delete/",
         MonitoringPlanDeleteView.as_view(), name='monitoring-plan-delete'),
    path("follow-up-plan/<str:slug>/delete/",
         FollowUpPlanDeleteView.as_view(), name='follow-up-plan-delete'),
    path("progress-note/<str:slug>/delete/",
         ProgressNoteDeleteView.as_view(), name='progress-note-delete'),



    path("pharmacist/<str:slug>/delete/", PharmacistDeleteView.as_view(),
         name='pharmacist-delete'),



]

pharmcare/templates/pharmcare/pharmaceutical_care_plans/patients-create.html
{% extends "base.html" %} {% block extra_css%}

{% endblock extra_css%} {% block content %}
{% load tailwind_filters %}
<main class="max-w-lg mx-auto mb-3">
    
  <div>
    <a class="hover:text-blue-500" href="{% url 'pharmcare:patients' %}">
        Go back to Patient page</a>
  </div>

  <div class="py-3 border-t border-gray-200">  
    <h1 class="text-4xl text-gray-800 ">Create a new Patient Summary information </h1 >
  </div>
  <form method="post" class="mt-5" action="{% url 'pharmcare:patients-create' %}">
          {% csrf_token %}
          {{ form|crispy }}
          <button
            class="w-full hover:text-white bg-blue-500 hover:bg-blue-600 px-3 py-1 rounded-md"
            type="submit"
          >Submit</button>
  </form>

</main>
{% endblock content %}

pharmcare/templates/pharmcare/pharmaceutical_care_plans/patients-delete.html
{% extends "base.html" %} {% block content %}
{% load tailwind_filters %}
<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="pharmcare w-full mb-6 py-6 border-b border-gray-200 justify-between 
      items-center ">
      <div>
      <h1 class="text-4xl text-gray-800">Patients Pharmaceutical Care Summary</h1>
      </div>
      <div class="text-gray-500 hover:text-blue-500">
      <a href="{% url 'pharmcare:patients' %}">Go to Patient's Monitoring Plan Page</a>

  </div>
        <h1 class="text-3xl text-gray-800" >Are you sure you want to delete this patient exclusive detail information?
            Note that this action won't be undone if you proceed.
        </h1>
    <form class="mt-5" method="post" action=".">
            {% csrf_token %} {{ form|crispy }}
            <button
            class="w-full  text-white bg-blue-500 border-0 py-1 px-6 
          focus:outline-none hover:bg-red-600 rounded"
         
            >
            Delete
            </button >
    </form>
  </div>
</section>


  {% endblock content %}

pharmcare/templates/pharmcare/pharmaceutical_care_plans/patients-detail.html
{% extends 'base.html' %} {% load static %} {% block content %}

<section class="text-gray-600 body-font overflow-hidden mt-0">
  <div class="container px-5 py-24 mx-auto">
    <div
      class="leads w-full mb-6 py-6 border-b border-gray-200 justify-between items-center"
    >
      <div>
        <h1 class="text-2xl text-gray-800">
          Patient Pharmaceutical Care Summary
        </h1>
      </div>
      <div class="text-gray-500 hover:text-blue-500">
        <a href="{% url 'pharmcare:patients-create' %}"
          >Go to Patient Summary Create Page</a
        >
      </div>
    </div>
    <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
      <table
        class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400"
      >
        <thead
          class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400"
        >
          <tr class="hover:text-gray-600">
            <th scope="col" class="p-4">
              <div class="flex items-center">
                <span>S/N</span>
              </div>
            </th>
            <th scope="col" class="px-6 py-3">Full name</th>
            <th scope="col" class="px-6 py-3">Patient unique code</th>
            <th scope="col" class="px-6 py-3">Has improved</th>
            <th scope="col" class="px-6 py-3">Progress note</th>
            <th scope="col" class="px-6 py-3">Medication changes</th>
            <th scope="col" class="px-6 py-3">Patients</th>
        
            <th scope="col" class="px-6 py-3">Analysis of clinical problem</th>
            <th scope="col" class="px-6 py-3">Monitoring plan</th>
            <th scope="col" class="px-6 py-3">Follow up plan</th>
            <th scope="col" class="px-6 py-3">Total</th>
            <th scope="col" class="px-6 py-3">Date created</th>
            <th scope="col" class="px-6 py-3">Action</th>
          </tr>
        </thead>
        <tbody>
          <tr
            class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600"
          >
            <td class="w-4 p-4">
              <div class="flex items-center">
                <span>{{patient_qs.id}}</span>
              </div>
            </td>
            {% for pt in patient_qs.patients.all %}
            <td class="px-6 py-4">{{ pt.get_full_name }}</td>
          {% endfor %}
            <td class="px-6 py-4">{{ patient_qs.patient_unique_code }}</td>
            <td class="px-6 py-4">{{ patient_qs.has_improved }}</td>
            <td class="px-6 py-4">{{ patient_qs.get_progress_note }}</td>
            <td class="px-6 py-4">{{ patient_qs.get_medication_changes }}</td>
          {% for pt in patient_qs.patients.all %} 
            <td class="px-6 py-4">{{ pt.patient.first_name }}</td>
          {% endfor %}
            <td class="px-6 py-4">{{ patient_qs.get_analysis_of_clinical_problem }}</td>
            <td class="px-6 py-4"> {{ patient_qs.get_monitoring_plan }} </td>
            <td class="px-6 py-4"> {{ patient_qs.get_follow_up_plan }} </td>
            {% for pt in patient_qs.patients.all %}
            <td class="px-6 py-4">₦{{ patient_qs.get_total }}</td>
            {%endfor %}
            <td class="px-6 py-4"> {{ patient_qs.date_created }} in UTC </td>

            <td class="flex items-center px-6 py-4">
              <a
                href="{% url 'pharmcare:patients-update' patient_qs.pk %}"
                class="pr-2 font-medium text-blue-600 dark:text-blue-500 hover:underline"
                >Edit</a
              >
              <a
                href=" {% url 'pharmcare:patients-delete' patient_qs.pk %}"
                class="font-medium text-red-600 dark:text-red-500 hover:underline ms-3"
                >Remove</a
              >
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</section>

{% endblock content %}

pharmcare/templates/pharmcare/pharmaceutical_care_plans/patients-list.html
{% extends 'base.html' %} 

{% load static %}
{% block extra_css %} 

{% endblock %}
   
{% block content %}


<section class="text-gray-600 body-font overflow-hidden mt-0">
  <div>{% include 'snippets/alert.html' %}</div>

  <div class="hero pt-5 px-5 ">{% include "pharmcare/snippets/search-patient.html" %}</div>
  <div class="container px-5 py-20 mx-auto">
    <div
      class="leads w-full mb-6 py-6 border-b border-gray-200 justify-between items-center"
    >

    <div>
        <h1 class="text-3xl text-gray-800">Patient Summary Information</h1>
      </div>

        {% if request.user.is_organizer or request.user.is_pharmacist %}
        <div class="text-gray-500 hover:text-blue-500">
          <a href="{% url 'pharmcare:patients-create' %}">Go to Patient's Create Page</a> 
        </div>
        {% endif %}
      </div>
      </div>
      
      <div class="flex flex-wrap m-4 pb-3">
    {% if patient_list|length == 0 %} 
          <p class="px-4 w-full text-2xl text-blue-800">
            Apologies, there is currently no patients with such 
            search you entered in our database. Kindly input a correct 
            data or contact the site owner. Thank you, Pharm {{ request.user.username |title }}!</p> 
         <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
      {% else %}
    
        <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
          <table
            class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400"
          >
            <thead
              class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400"
            >
              <tr class="hover:text-gray-600">
                <th scope="col" class="p-4">
                  <div class="flex items-center">
                    <span>S/N</span>
                  </div>
                </th>

                <th scope="col" class="px-6 py-3">Full name</th>
                <th scope="col" class="px-6 py-3">Patient unique code</th>
                <th scope="col" class="px-6 py-3">Has improved</th>
                <th scope="col" class="px-6 py-3">Progress note</th>
                <th scope="col" class="px-6 py-3">Medication changes</th>
                <th scope="col" class="px-6 py-3">Patients
                 </th>
                <th scope="col" class="px-6 py-3">Analysis of clinical problem</th>
                <th scope="col" class="px-6 py-3">Monitoring plan</th>
                <th scope="col" class="px-6 py-3">Follow up plan</th>
                <th scope="col" class="px-6 py-3">Total</th>
                <th scope="col" class="px-6 py-3">Date created</th>
                <th scope="col" class="px-6 py-3">Action</th>
              </tr>
            </thead>
           
            <tbody>
             {% for patient_qs in patient_list %}
              <tr
                class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 
                hover:bg-gray-50 dark:hover:bg-gray-600"
              >

                 <td class="w-4 p-4">
                    <div class="flex items-center">
                      <span>{{forloop.counter }}</span>
                    </div>
                  </td>
                {% for pt in patient_qs.patients.all %}
                  <td class="px-6 py-4">{{ pt.get_full_name }}</td>
                {% endfor %}
                  <td class="px-6 py-4">{{ patient_qs.patient_unique_code }}</td>
                  <td class="px-6 py-4">{{ patient_qs.has_improved }}</td>
                  <td class="px-6 py-4">{{ patient_qs.get_progress_note }}</td>
                  <td class="px-6 py-4">{{ patient_qs.get_medication_changes }}</td>
                {% for pt in patient_qs.patients.all %} 
                  <td class="px-6 py-4">{{ pt.patient.first_name }}</td>
                {% endfor %}
                  <td class="px-6 py-4">{{ patient_qs.get_analysis_of_clinical_problem }}</td>
                  <td class="px-6 py-4"> {{ patient_qs.get_monitoring_plan }} </td>
                  <td class="px-6 py-4"> {{ patient_qs.get_follow_up_plan }} </td>
                  
                  {% if patient_qs.discount  > 1 %}
                  <td class="px-6 py-4">₦{{ patient_qs.get_total }}</td>
                  {% else %}
                  <td class="px-6 py-4">₦{{patient_qs.get_total_when_no_discount }}</td>
                
                  {%endif %}
           
                  <td class="px-6 py-4"> {{ patient_qs.date_created }} in UTC </td>
            
                  <td class="flex items-center px-6 py-4">
                    <a
                      href="
                      {% url "pharmcare:patients-detail" patient_qs.pk %} 
                          
                      "
                      class="pr-2 font-medium text-blue-600 dark:text-blue-500 hover:underline"
                      >For Further Details</a
                    >
                  </td>
            </tr>
            </tbody>
            
          {% endfor %}
           </table>
        
     </div>
 
        
      <div class="py-4"> {% include 'pharmcare/snippets/paginate-patients.html' %}</div>
         {% endif %}
 </section>
  


{% endblock content %} 

pharmcare/templates/pharmcare/pharmaceutical_care_plans/patients-update.html
{% extends "base.html" %} {% block extra_css%}

{% endblock extra_css%} {% block content %}
{% load tailwind_filters %}
<main class="max-w-lg mx-auto mb-3">
    
  <a class="hover:text-blue-500 pt-heading-info"
     href="{% url 'pharmcare:patients' %}">Go back to Patient Pharmaceutical Care page</a>
  <div class="py-3 border-t border-gray-200">  

    {% for pt in patient_qs.patients.all %} 
    <h1 class="text-4xl text-gray-800  create-pt-heading">Update {{ pt.get_full_name }}'s data.</h1 >
    {% endfor %}
  </div>
  <form method="post" class="mt-5 create-pt" action=".">
          {% csrf_token %}
          {{ form|crispy }}
          <button
            class="w-full hover:text-white bg-blue-500 hover:bg-blue-600 px-3 py-1 rounded-md"
            type="submit"
          >Submit</button>
  </form>

</main>
{% endblock content %}