chats/urls.py
from django.urls import path
from .views import ChatView

app_name = 'chats'

urlpatterns = [
    path('', ChatView.as_view(), name='chats')
]

musics/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView

)
from django.views.generic import TemplateView
from django.urls import path, include
from leads.views import LandingPageView, SignUpView

admin.site.site_header = 'Django_Test Enterprise'
admin.site.index_title = 'Django_Test Administration'


urlpatterns = [
    path('admin/', admin.site.urls),
    
    # Local apps
    path('', LandingPageView.as_view(), name='landing-page'),
    path('song/', include('songs.urls', namespace='songs')),
    path('leads/', include("leads.urls", namespace='leads')),
    path("agents/", include("agents.urls", namespace='agents')),

    # Registration URL - inherited for django.contrib.auths views
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    
    
    # third party
    path('accounts/', include('allauth.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path("__reload__/", include("django_browser_reload.urls")),


]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

pharmaceuticals/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
#from django.conf.urls.defaults import *
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView

)
from django.views.generic import TemplateView
from django.urls import path, include
from leads.views.leads import LandingPageView, SignUpView

admin.site.site_header = 'MedConnect Pharmaceuticals'
admin.site.index_title = 'Django_Test Administration'


urlpatterns = [
    path('admin/', admin.site.urls),

    # Local apps
    path('', LandingPageView.as_view(), name='landing-page'),
    path('song/', include('songs.urls', namespace='songs')),
     path('accounts/', include('allauth.urls')),
    path('leads/', include("leads.urls", namespace='leads')),
    path("agents/", include("agents.urls", namespace='agents')),
    path('pharmcare/', include('pharmcare.urls', namespace='pharmcare')),
    path('chats/', include('chats.urls', namespace='chats')),
    path('staff-attendance/', include('staff.urls', namespace='staff')),



    # Registration URL - inherited for django.contrib.auths views
   # path('login/', LoginView.as_view(), name='login'),
    #path('logout/', LogoutView.as_view(), name='logout'),
    #path('signup/', SignUpView.as_view(), name='signup'),
    #path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    #path('password-reset-done/', PasswordResetDoneView.as_view(),
     #    name='password_reset_done'),
   # path('password-reset-confirm/<uidb64>/<token>/',
    #     PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    #path('password-reset-complete/', PasswordResetCompleteView.as_view(),
     #    name='password_reset_complete'),


    # third party
    path('accounts/', include('allauth.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path("__reload__/", include("django_browser_reload.urls")),


]


handler404 = 'pharmcare.views.patient_details.error_404'
handler500 =  'pharmcare.views.patient_details.error_500'
handler403 =  'pharmcare.views.patient_details.error_403'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

pharmcare/urls.py
from django.urls import path
from pharmcare.views.pharmacists import *

from pharmcare.views.patient_details import (
    PatientDetailListView,
    PatientDetailCreateView,
    PatientDetailView,
    UpdatePatientDetailView,
    DeletePatientDetailView,
)

from pharmcare.views.medication_history import (
    MedicationHistoryListView,
    MedicationHistoryCreateView,
    MedicationHistoryDeleteView,
    MedicationHistoryUpdateView,
    MedicationHistoryDetailView,
)

from pharmcare.views.medication_changes import (
    MedicationChangesListView,
    MedicationChangesCreateView,
    MedicationChangesDetailView,
    MedicationChangesUpdateView,
    MedicationChangesDeleteView,
)
from pharmcare.views.monitoring_plans import (

    MonitoringPlanListView,
    MonitoringPlanCreateView,
    MonitoringPlanDetailView,
    MonitoringPlanUpdateView,
    MonitoringPlanDeleteView,

)

from pharmcare.views.analysis_of_cp import (

    AnalysisOfClinicalProblemListView,
    AnalysisOfClinicalProblemCreateView,
    AnalysisOfClinicalProblemDetailView,
    AnalysisOfClinicalProblemUpdateView,
    AnalysisOfClinicalProblemDeleteView,

)

from pharmcare.views.pharmaceutical_care_plan import (
    PatientSummaryListView,
    PatientSummaryCreateView,
    delete_patient_summary,
    PatientSummaryDetailView,
    PatientSummaryUpateView,

)

from pharmcare.views.progress_notes import (

    ProgressNoteListView,
    ProgressNoteCreateView,
    ProgressNoteDetailView,
    ProgressNoteUpdateView,
    ProgressNoteDeleteView,
)

from pharmcare.views.follow_up_plans import (

    FollowUpPlanListView,
    FollowUpPlanCreateView,
    FollowUpPlanDetailView,
    FollowUpPlanUpdateView,
    FollowUpPlanDeleteView,

)

from pharmcare.views.patients import (
    PatientListView,
    PatientCreateView,
    PatientUpateView,
    delete_patient_view,
    PatientsDetailView
)


app_name = 'pharmcare'

urlpatterns = [
    # Pharmcare URI

    # pharmcare list URIs
    path('', PatientDetailListView.as_view(), name='patient'),
    path('medication-history/', MedicationHistoryListView.as_view(),
         name='medication-history'),
    path('patient-info/', PatientListView.as_view(), name='patient-info'),
    path('patient-list/', PatientSummaryListView.as_view(), name='patients'),
    path('medication-changes/', MedicationChangesListView.as_view(),
         name='medication-changes'),
    path('analysis-of-clincal-problem/',
         AnalysisOfClinicalProblemListView.as_view(), name='analysis-of-cp'),
    path('monitoring-plan/', MonitoringPlanListView.as_view(),
         name='monitoring-plan'),
    path('follow-up-plan/', FollowUpPlanListView.as_view(), name='follow-up-plan'),
    path('progress-note/', ProgressNoteListView.as_view(), name='progress-notes'),


    path('pharmacist/', PharmacistListView.as_view(), name="pharmacist-list"),


    # pharmcare create uris
    path('patient-create/', PatientDetailCreateView.as_view(), name='patient-create'),
    path('patient-info-create/', PatientCreateView.as_view(),
         name='patients-info-create'),
    path('medication-history-create/', MedicationHistoryCreateView.as_view(),
         name='medication-history-create'),
    path('patients-create/',  PatientSummaryCreateView.as_view(),
         name='patients-create'),
    path('medication-changes-create/', MedicationChangesCreateView.as_view(),
         name='medication-changes-create'),
    path('analysis-of-clincal-problem-create/',
         AnalysisOfClinicalProblemCreateView.as_view(), name='analysis-of-cp-create'),
    path('monitoring-plan-create/', MonitoringPlanCreateView.as_view(),
         name='monitoring-plan-create'),
    path('follow-up-plan-create/', FollowUpPlanCreateView.as_view(),
         name='follow-up-plan-create'),
    path('progress-note-create/', ProgressNoteCreateView.as_view(),
         name='progress-note-create'),

    path('pharmacist-create/', PharmacistCreateView.as_view(),
         name="pharmacist-create"),


    # pharmcare detail uris
    path('<str:slug>/', PatientDetailView.as_view(), name='patient-detail'),
    path('patient-info/<str:slug>/', PatientsDetailView.as_view(),
         name='patients-info-detail'),
    path("medication-changes/<str:slug>/",
         MedicationChangesDetailView.as_view(), name='medication-changes-detail'),
    path('medication-history/<int:pk>/', MedicationHistoryDetailView.as_view(),
         name='medication-history-detail'),

    path("analysis-of-clincal-problem/<str:slug>/",
         AnalysisOfClinicalProblemDetailView.as_view(), name='analysis-of-cp-detail'),
    path('patient-list/<int:pk>/',
         PatientSummaryDetailView.as_view(), name='patients-detail'),

    path("monitoring-plan/<str:slug>/",
         MonitoringPlanDetailView.as_view(), name='monitoring-plan-detail'),
    path("follow-up-plan/<str:slug>/", FollowUpPlanDetailView.as_view(),
         name='follow-up-plan-detail'),
    path("progress-note/<str:slug>/", ProgressNoteDetailView.as_view(),
         name='progress-note-detail'),

    path("pharmacist/<str:slug>/", PharmacistDetailView.as_view(),
         name='pharmacist-detail'),

    # pharmcare update uris
    path('<str:slug>/patient-update/',
         UpdatePatientDetailView.as_view(), name='patient-update'),
    path('medication-history/<int:pk>/medication-history-update/',
         MedicationHistoryUpdateView.as_view(), name='medication-history-update'),
    path('patient-list/<int:pk>/patients-update/',
         PatientSummaryUpateView.as_view(), name='patients-update'),
    path('patient-info/<str:slug>/update/',
         PatientUpateView.as_view(), name='patients-info-update'),
    path("medication-changes/<str:slug>/update/",
         MedicationChangesUpdateView.as_view(), name='medication-changes-update'),
    path("analysis-of-clincal-problem/<str:slug>/update/",
         AnalysisOfClinicalProblemUpdateView.as_view(), name='analysis-of-cp-update'),
    path("monitoring-plan/<str:slug>/update/",
         MonitoringPlanUpdateView.as_view(), name='monitoring-plan-update'),
    path("follow-up-plan/<str:slug>/update/",
         FollowUpPlanUpdateView.as_view(), name='follow-up-plan-update'),
    path("progress-note/<str:slug>/update/",
         ProgressNoteUpdateView.as_view(), name='progress-note-update'),



    path("pharmacist/<str:slug>/update/", PharmacistUpdateView.as_view(),
         name='pharmacist-update'),


    # pharmcare delete uris
    path('<str:slug>/patient-delete/',
         DeletePatientDetailView.as_view(), name='patient-delete'),

    path('medication-history/<int:pk>/medication-history-delete/',
         MedicationHistoryDeleteView.as_view(), name='medication-history-delete'),

    path('patient-list/<int:pk>/patients-delete/',
         delete_patient_summary, name='patients-delete'),
    path('patients-info/<str:slug>/delete/',
         delete_patient_view, name='patient-info-delete'),

    path("medication-changes/<str:slug>/delete/",
         MedicationChangesDeleteView.as_view(), name='medication-changes-delete'),
    path("analysis-of-clincal-problem/<str:slug>/delete/",
         AnalysisOfClinicalProblemDeleteView.as_view(), name='analysis-of-cp-delete'),
    path("monitoring-plan/<str:slug>/delete/",
         MonitoringPlanDeleteView.as_view(), name='monitoring-plan-delete'),
    path("follow-up-plan/<str:slug>/delete/",
         FollowUpPlanDeleteView.as_view(), name='follow-up-plan-delete'),
    path("progress-note/<str:slug>/delete/",
         ProgressNoteDeleteView.as_view(), name='progress-note-delete'),



    path("pharmacist/<str:slug>/delete/", PharmacistDeleteView.as_view(),
         name='pharmacist-delete'),



]

staff/urls.py
from django.urls import path
from .views.attendance import (
    AttendanceListView,
    AttendanceCreateView,
    AttendanceDetailView,
    AttendanceUpdateView,
    AttendanceDeleteView,
    
)

from .views.management import (
    ManagementAssignedView,
    
    ManagementDetailView,
    ManagementListView,
    ManagementCreateView,
    ManagementDeleteView,
    ManagementUpdateView
)

app_name = 'staff'


urlpatterns = [
    # list uri - staff
    path('', AttendanceListView.as_view(), name='attendance'),
    path('management/', ManagementListView.as_view(), name='management-list'), 
    
    # create uri - staff
    path('attendance-create/', AttendanceCreateView.as_view(), name='attendance-create'),
    path('management-create/', ManagementCreateView.as_view(), name='management-create'),
    
    path('<str:slug>/', AttendanceDetailView.as_view(), name='attendance-detail'),
    path('management/<str:slug>/', ManagementDetailView.as_view(), name='management-detail'),
    
    path('<str:slug>/update/', AttendanceUpdateView.as_view(), name='attendance-update'),
    path('management/<str:slug>/update/', ManagementUpdateView.as_view(), name='management-update'),
    
    path('<str:slug>/delete/', AttendanceDeleteView.as_view(), name='attendance-delete'),
    path('management/<str:slug>/delete/', ManagementDeleteView.as_view(), name='management-delete'),
   
    path('<str:slug>/assigned-management/', ManagementAssignedView.as_view(), name='assigned-management')
]
    
   
   

 

staff/forms.py
from django import forms
from .models import Management, Attendance
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()


class AttendanceModelForm(forms.ModelForm):
    """ A form class responsible for the staff daily records form creation in the database
    in realtime"""
    class Meta:
        model = Attendance
        fields = [
            'full_name',
            'sign_in_time',
            'sign_out_time'
        
        ]

class ManagementModelForm(forms.ModelForm):
    """ form class that handles organization management form for the attendance
    if the user is granted access."""
    class Meta:
        model = User
        fields = [
       
            'username',
            'first_name',
            "last_name",
            'phone_number',
            'email',
               
        ]
        
        labels = {
            "username": "Enter your username",
            "first_name": "Enter your first name",
            "last_name": "Enter your last name",
            "phone_number": "Enter your phone number",
            'email': 'Enter your email',
        }


class ManagementAssignedForm(forms.Form):
    management = forms.ModelChoiceField(queryset=Management.objects.none())

    def __init__(self, *args, **kwargs):

        request = kwargs.pop('request')
        management = Management.objects.filter(organization=request.user.userprofile)
      
        super(ManagementAssignedForm, self).__init__(*args, **kwargs)
       
        self.fields['management'].queryset = management

staff/templates/staff/attendance-create.html
{% extends "base.html" %} {% block extra_css%}

{% endblock extra_css%} {% block content %}
{% load tailwind_filters %}

<main class="max-w-lg mx-auto mb-3">
    
  <div>
    <a class="hover:text-blue-500" href="{% url 'staff:attendance-create' %}">
        Go back to Attendance page</a>
  </div>

  <div class="py-3 border-t border-gray-200">  
    <h1 class="text-4xl text-gray-800 ">Create a new Staff Attendance information </h1 >
  </div>
  <form method="post" class="mt-5" action="{% url 'staff:attendance-create' %}">
          {% csrf_token %}
          {{ form|crispy }}
          <button
            class="w-full hover:text-white bg-blue-500 hover:bg-blue-600 px-3 py-1 rounded-md"
            type="submit"
          >Submit</button>
  </form>


  
</main>
{% endblock content %}

staff/templates/staff/attendance-delete.html
{% extends "base.html" %} {% block content %}
{% load tailwind_filters %}
<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="pharmcare w-full mb-6 py-6 border-b border-gray-200 justify-between 
      items-center ">
      <div>
      <h1 class="text-4xl text-gray-800">Staff Attendance Register</h1>
      </div>
      <div class="text-gray-500 hover:text-blue-500">
      <a href="{% url 'staff:attendance-create' %}">Go to Staff Attendance Create Page</a>

  </div>
        <h1 class="text-2xl text-gray-800" >Are you sure you want to delete this staff from the attendance register?</h1>
    <form class="mt-5" method="post" action=".">
            {% csrf_token %} {{ form|crispy }}
            <button href="{% url 'staff:attendance-delete' attendance.slug %}" {% comment %} {% url 'pharmcare:patient-delete' patient.pk %} {% endcomment %}
            class="w-1/2  text-white bg-blue-500 border-0 py-1 px-6 
          focus:outline-none hover:bg-red-600 rounded"
         
            >
            Delete
            </button >
    </form>
  </div>
</section>


  {% endblock content %}

staff/templates/staff/attendance-list.html
{% extends 'base.html' %} 

{% load static %}
{% block extra_css %} 

{% endblock %}
   
{% block content %}

<section class="text-gray-600 body-font overflow-hidden mt-0">
  <div>{% include 'snippets/alert.html' %}</div>

  <div class="hero pt-5 px-5 ">{% include "staff/snippets/search-attendance.html" %}</div>
  <div class="container px-5 py-20 mx-auto">
    <div
      class="leads w-full mb-6 py-6 border-b border-gray-200 justify-between items-center"
    >
      <div>
        <h1 class="text-3xl pb-2 text-gray-800">Staff Attendance Register </h1>

        
      <button id="dropdownDelayButton" data-dropdown-toggle="dropdownDelay" 
      data-dropdown-delay="500" data-dropdown-trigger="hover" class="text-white bg-blue-700 
      hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium 
      rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:bg-blue-600
       dark:hover:bg-blue-700 dark:focus:ring-blue-800" type="button">Attendance Register
        <svg class="w-2.5 h-2.5 ms-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
        </svg>
        </button>
        
        <!-- Dropdown menu -->
        <div id="dropdownDelay" class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700">
            <ul class="py-2 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownDelayButton">
              <li>
                <a href="{% url 'staff:attendance' %}" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">View Attendance </a>
              </li>
            {% comment %}   <li>
                <a href="{% url 'staff:assigned-management' %}" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">View Attendance </a>
              for pt in p:
              </li> {% endcomment %}
              {% if request.user.is_organizer %}
              <li>
                <a href="{% url 'staff:management-list' %}" 
                class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">
                View Management </a>
              </li>
              {% endif %}
              <li>
            </ul>
          </div>
      </div>

        {% if request.user.is_organizer or request.user.is_management %}
        <div class="text-gray-500 hover:text-blue-500">
          <a href="{% url 'staff:attendance-create' %}">Go to Attendance Create Page</a> 
        </div>
        {% endif %}
      </div>
      <div class="flex flex-wrap m-4 pb-3">
        {% if attendance|length == 0 %}
          <p class="px-4 w-full text-2xl text-blue-800">
            Apologies, there is currently no staff with such 
            search you entered in our database. Kindly input a correct 
            data or contact the site owner. Thank you,  {{ request.user.username|title }}!</p> 
        {% else %}
        <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
          <table
            class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400"
          >
            <thead
              class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400"
            >
              <tr class="hover:text-gray-600">
                <th scope="col" class="p-4">
                  <div class="flex items-center">
                    <span>S/N</span>
                  </div>
                </th>
                <th scope="col" class="px-6 py-3">Full name</th>
                <th scope="col" class="px-6 py-3">Sign in time</th>
                <th scope="col" class="px-6 py-3">Sign out time</th>
                <th scope="col" class="px-6 py-3">staff daily unique attendance ref</th>
                <th scope="col" class="px-6 py-3">Sign in Date</th>
             {% comment %}    <th scope="col" class="px-6 py-3">Organization</th> {% endcomment %}
                <th scope="col" class="px-6 py-3">Action</th>
              </tr>
            </thead>
         {% for staff in attendance %}
            <tbody>
              <tr
                class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 
                hover:bg-gray-50 dark:hover:bg-gray-600"
              >
                <td class="w-4 p-4">
                  <div class="flex items-center">
                    <span>{{staff.id }}</span>
                  </div>
                </td>
                <td class="px-6 py-4">{{ staff.full_name|title }}</td>
                <td class="px-6 py-4">{{ staff.get_sign_in_time }}</td>
                <td class="px-6 py-4">{{ staff.get_sign_out_time }}</td>
                <td class="px-6 py-4">{{ staff.staff_attendance_ref }}</td>
                <td class="px-6 py-4">{{ staff.date_added  }}</td>
             {% comment %}    <td class="px-6 py-4">{{ staff.organization|title }}</td> {% endcomment %}
              
                <td class="flex items-center px-6 py-4">
                   <a href="{% url "staff:attendance-detail" staff.slug %}"
                      class="pr-2 font-medium text-blue-600 dark:text-blue-500 hover:underline" 
                      >For further Details
                    </a>
                </td>
            </tr>
            </tbody>
          
           {% endfor %}
        </table>
      </div>
  
  
    </div>
      <div class="px-3 pb-3">{% include 'staff/snippets/paginate-attendance.html' %} </div>
    </div>
        {% endif %}
    {% if unassigned_management.exists %}

      
          {% for staff in unassigned_management %}
        
      <div class="mt-5 flex flex-wrap -m-4">
         
          <div class="p-4 w-full text-3xl text-gray-800">
            <h1>Unassigned Staff Attendance Record</h1>
          </div>
          <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
            <table
              class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400"
            >
              <thead
                class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400"
              >
                <tr class="hover:text-gray-600">
                  <th scope="col" class="p-4">
                    <div class="flex items-center">
                      <span>S/N</span>
                    </div>
                  </th>
                   <th scope="col" class="px-6 py-3">Full name</th>
                    <th scope="col" class="px-6 py-3">Sign in time</th>
                    <th scope="col" class="px-6 py-3">Sign out time</th>
                    <th scope="col" class="px-6 py-3">staff daily unique attendance ref</th>
                    <th scope="col" class="px-6 py-3">Organization</th>
                    <th scope="col" class="px-6 py-3">Action</th>
                </tr>
              </thead>
        
              <tbody>
                <tr
                  class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 
                  hover:bg-gray-50 dark:hover:bg-gray-600"
                >
                  <td class="w-4 p-4">
                    <div class="flex items-center">
                      <span>{{staff.id }}</span>
                    </div>
                  </td>
                  <td class="px-6 py-4">{{ staff.full_name }}</td>
                  <td class="px-6 py-4">{{ staff.sign_in_time }}</td>
                  <td class="px-6 py-4">{{ staff.sign_out_time }}</td>
                  <td class="px-6 py-4">{{ staff.staff_attendance_ref }}</td>
                  <td class="px-6 py-4">{{ staff.organization }}</td>
                  <td class="flex items-center px-6 py-4">
                    <a
                      href="{{staff.get_absolute_url }}"
                      class="pr-2 font-medium text-blue-600 dark:text-blue-500 hover:underline"
                      >For further Details</a
                    >
                  </td>
              </tr>
              </tbody>
            </table>
          </div>
          {% empty %}
          <p>There are currently no staff. Thank you.</p>
          {% endfor %}
        </div>

        <div class="py-4"> {% include 'staff/snippets/paginate-attendance.html' %}</div>
    {% endif %}
      
  </section>
  


{% endblock content %} 

staff/templates/staff/attendance-update.html
{% extends "base.html" %} {% block extra_css%}

{% endblock extra_css%} {% block content %}
{% load tailwind_filters %}
<main class="max-w-lg mx-auto mb-3">
    
  <a class="hover:text-blue-500" href="{% url 'staff:attendance' %}">
    Go back to Staff Attendance page</a>
  <div class="py-3 border-t border-gray-200">  
    <h1 class="text-4xl text-gray-800  create-pt-heading
    ">Update Staff Attendance data.</h1 >
  </div>
  <form method="post" class="mt-5 pt-create" action=".">
          {% csrf_token %}
          {{ form|crispy }}
          <button
            class="w-full hover:text-white bg-blue-500 hover:bg-blue-600 px-3 py-1 rounded-md"
            type="submit"
          >Submit</button>
  </form>

</main>
{% endblock content %}

staff/templates/staff/management-create.html
{% extends "base.html" %} {% block extra_css%}

{% endblock extra_css%} {% block content %}
{% load tailwind_filters %}
<main class="max-w-lg mx-auto mb-3">
    
  <div>
    <a class="hover:text-blue-500" href="{% url 'staff:management-list' %}">
        Go back to Management page</a>
  </div>

  <div class="py-3 border-t border-gray-200">  
    <h1 class="text-4xl text-gray-800 ">Create a new Management information </h1 >
  </div>
  <form method="post" class="mt-5" action="{% url 'staff:management-create' %}">
          {% csrf_token %}
          {{ form|crispy }}
          <button
            class="w-full hover:text-white bg-blue-500 hover:bg-blue-600 px-3 py-1 rounded-md"
            type="submit"
          >Submit</button>
  </form>

</main>
{% endblock content %}

staff/templates/staff/management-delete.html
{% extends "base.html" %} {% block content %}
{% load tailwind_filters %}
<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="pharmcare w-full mb-6 py-6 border-b border-gray-200 justify-between 
      items-center ">
      <div>
      <h1 class="text-4xl text-gray-800">Management (Branch) </h1>
      </div>
      <div class="text-gray-500 hover:text-blue-500">
      <a href="{% url 'staff:management-create' %}">Go to Management Create Page</a>

  </div>
        <h1 class="text-2xl text-gray-800" >Are you sure you want to delete this manager from keeping your attendance register?</h1>
    <form class="mt-5" method="post" action=".">
            {% csrf_token %} {{ form|crispy }}
            <button href="{% url 'staff:management-delete' object.slug %}" {% comment %} {% url 'pharmcare:patient-delete' patient.pk %} {% endcomment %}
            class="w-1/2  text-white bg-blue-500 border-0 py-1 px-6 
          focus:outline-none hover:bg-red-600 rounded"
         
            >
            Delete
            </button >
    </form>
  </div>
</section>


  {% endblock content %}